export const API_ERROR_CODES = {
  ADMIN_AUTH_UNAVAILABLE: "ADMIN_AUTH_UNAVAILABLE",
  BOOK_CATALOG_WRITE_FAILED: "BOOK_CATALOG_WRITE_FAILED",
  BOOK_EDITION_NOT_FOUND: "BOOK_EDITION_NOT_FOUND",
  CART_VALIDATION_FAILED: "CART_VALIDATION_FAILED",
  CATALOG_READ_FAILED: "CATALOG_READ_FAILED",
  CUSTOMER_AUTH_FAILED: "CUSTOMER_AUTH_FAILED",
  CUSTOMER_PROFILE_UNAVAILABLE: "CUSTOMER_PROFILE_UNAVAILABLE",
  CUSTOMER_READ_FAILED: "CUSTOMER_READ_FAILED",
  FORBIDDEN: "FORBIDDEN",
  INVENTORY_ADJUSTMENT_FAILED: "INVENTORY_ADJUSTMENT_FAILED",
  INVENTORY_READ_FAILED: "INVENTORY_READ_FAILED",
  ORDER_CREATE_FAILED: "ORDER_CREATE_FAILED",
  ORDER_INVALID_TRANSITION: "ORDER_INVALID_TRANSITION",
  ORDER_NOT_FOUND: "ORDER_NOT_FOUND",
  ORDER_READ_FAILED: "ORDER_READ_FAILED",
  ORDER_UPDATE_FAILED: "ORDER_UPDATE_FAILED",
  OUT_OF_STOCK: "OUT_OF_STOCK",
  PRODUCT_NOT_FOUND: "PRODUCT_NOT_FOUND",
  PROMOTION_INVALID: "PROMOTION_INVALID",
  PROMOTION_READ_FAILED: "PROMOTION_READ_FAILED",
  PROMOTION_WRITE_FAILED: "PROMOTION_WRITE_FAILED",
  SIGN_OUT_FAILED: "SIGN_OUT_FAILED",
  UNAUTHORIZED: "UNAUTHORIZED",
  VALIDATION_ERROR: "VALIDATION_ERROR",
} as const;

export type ApiErrorCode =
  (typeof API_ERROR_CODES)[keyof typeof API_ERROR_CODES];
