export const API_ERROR_CODES = {
  ADMIN_AUTH_UNAVAILABLE: "ADMIN_AUTH_UNAVAILABLE",
  CART_VALIDATION_FAILED: "CART_VALIDATION_FAILED",
  CATALOG_READ_FAILED: "CATALOG_READ_FAILED",
  FORBIDDEN: "FORBIDDEN",
  ORDER_CREATE_FAILED: "ORDER_CREATE_FAILED",
  ORDER_NOT_FOUND: "ORDER_NOT_FOUND",
  ORDER_READ_FAILED: "ORDER_READ_FAILED",
  ORDER_UPDATE_FAILED: "ORDER_UPDATE_FAILED",
  OUT_OF_STOCK: "OUT_OF_STOCK",
  PRODUCT_NOT_FOUND: "PRODUCT_NOT_FOUND",
  SIGN_OUT_FAILED: "SIGN_OUT_FAILED",
  UNAUTHORIZED: "UNAUTHORIZED",
  VALIDATION_ERROR: "VALIDATION_ERROR",
} as const;

export type ApiErrorCode =
  (typeof API_ERROR_CODES)[keyof typeof API_ERROR_CODES];
